#!/usr/bin/env python3
"""Programmatic builder for method-explorer simulation scenarios.

WHY THIS EXISTS
---------------
Hand-authored scenarios relied on a fragile "labeling contract": first-match
substring ordering plus carefully reserved, non-overlapping action words (e.g.
'counter' had to be listed before 'sign' because "counter" ⊄ "sign" but a
counter-sign action contains both). Getting that ordering wrong silently breaks the
intended deterministic path — the #1 footgun in scenario construction.

This builder removes the footgun:
  1. ENFORCES non-overlapping method tags (no tag is a substring of another), which
     makes first-match ordering irrelevant — the rules are unambiguous in any order.
  2. CO-GENERATES the scenario JSON and the matching prompt fragment, so the action
     labels the planner is told to use always match the scenario's match substrings
     (no synonym drift).
  3. Provides a lightweight expected-terminal oracle + consistency validation.

Verdict vocabulary (de-facto): outcome ∈ {tombstone, progress, success}; default
'tombstone' (fail-closed). Full grammar: references/scenario-grammar.md.

NOTE: the oracle is *probabilistic* — it states what SHOULD happen if the planner
walks the declared path; the LLM-in-the-loop means tests still assert by pass-rate
(N>=3), never a single run.
"""
import os
import sys
from dataclasses import dataclass
from typing import List, Optional

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "scripts"))
import envelope  # noqa: E402 — the canonical invocation contract (single source)

# Phonetic alphabet: mutually non-overlapping tags (no one is a substring of another).
PHONETIC = ["alfa", "bravo", "charlie", "delta", "echo", "foxtrot", "golf", "hotel",
            "india", "juliett", "kilo", "lima", "mike", "november", "oscar", "papa"]
VALID_OUTCOMES = {"tombstone", "progress", "success"}
VALID_DEFAULTS = {"tombstone", "progress", "passthrough"}


@dataclass
class Method:
    tag: str                                   # unique, non-overlapping action label
    outcome: str                               # tombstone | progress | success
    opens: Optional[List[str]] = None          # tags unlocked into the frontier
    on_occurrence: Optional[int] = None        # fire on the Nth matching attempt
    after_tombstones: Optional[int] = None     # fire only once >=N tombstones journaled
    reason: str = ""


def _overlap(a: str, b: str) -> bool:
    a, b = a.lower(), b.lower()
    return a in b or b in a


def validate(methods: List[Method], default: str) -> None:
    """Raise if the method set would not be deterministic under first-match matching."""
    if default not in VALID_DEFAULTS:
        raise ValueError(f"bad default {default!r}; want one of {sorted(VALID_DEFAULTS)}")
    tags = [m.tag for m in methods]
    if len(tags) != len({t.lower() for t in tags}):
        raise ValueError("duplicate method tags")
    for i, a in enumerate(tags):
        for b in tags[i + 1:]:
            if _overlap(a, b):
                raise ValueError(
                    f"overlapping tags {a!r} and {b!r}: one is a substring of the other, "
                    "which breaks first-match determinism. Use distinct tags (PHONETIC is safe)."
                )
    known = {t.lower() for t in tags}
    for m in methods:
        if m.outcome not in VALID_OUTCOMES:
            raise ValueError(f"{m.tag}: bad outcome {m.outcome!r}")
        for o in (m.opens or []):
            if o.lower() not in known:
                raise ValueError(f"{m.tag}: opens unknown tag {o!r}")


def build_scenario(intent: str, methods: List[Method], default: str = "tombstone",
                   notes: str = "") -> dict:
    """Return a valid, deterministic scenario dict from a method list."""
    validate(methods, default)
    # Order tombstone -> progress -> success (cosmetic; non-overlap makes order moot).
    rank = {"tombstone": 0, "progress": 1, "success": 2}
    rules = []
    for m in sorted(methods, key=lambda m: rank[m.outcome]):
        rule = {"id": f"r-{m.tag}", "match": {"action_contains": m.tag},
                "outcome": m.outcome,
                "reason": m.reason or f"{m.tag}: declared {m.outcome}"}
        if m.opens:
            rule["opens"] = list(m.opens)
        if m.on_occurrence is not None:
            rule["on_occurrence"] = m.on_occurrence
        if m.after_tombstones is not None:
            rule["after_tombstones"] = m.after_tombstones
        rules.append(rule)
    return {"intent": intent, "default": default,
            "notes": notes or "generated by scenario_builder.py", "rules": rules}


def method_list_prompt(methods: List[Method]) -> str:
    """Prompt fragment telling the planner to label each method with its exact tag, so
    its action text matches the scenario's match substrings (kills synonym drift)."""
    tags = ", ".join(f'"{m.tag}"' for m in methods)
    return ("When you consider or attempt a method, LABEL it in your action text with "
            f"exactly one of these tags (verbatim): {tags}. The simulation resolves a "
            "node's outcome by which tag its action text contains.")


def canonical_backtrack_methods():
    """The canonical 4-method backtrack scenario — two network siblings tombstone, the
    cache progresses, verify succeeds. Shared by test_00 / test_c1 / test_16 / demo.py so
    they stay in sync (was duplicated 6x)."""
    return [
        Method("alfa", "tombstone", reason="primary network source is down"),
        Method("bravo", "tombstone", reason="mirror network source is down"),
        Method("charlie", "progress", opens=["delta"], reason="local cache hit"),
        Method("delta", "success", reason="verified valid JSON with key ok"),
    ]


def canonical_resume_methods():
    """The 3-method resume variant (alfa dead, charlie → delta). Shared by test_10."""
    return [
        Method("alfa", "tombstone", reason="primary source down"),
        Method("charlie", "progress", opens=["delta"], reason="local cache hit"),
        Method("delta", "success", reason="verified valid result"),
    ]


def build_prompt(intent: str, methods: List[Method], slug: str, meanings: dict = None,
                 mode: str = "sim", plans_dir: str = "/opt/data/plans", extra: str = "") -> str:
    """Full, runnable prompt for a builder-generated scenario — keeps prompt + scenario
    in sync so generated cases need no hand-written framing. `meanings` optionally maps
    tag -> natural description (e.g. {'alfa': 'fetch from the primary source'})."""
    head = ("Use the method-explorer skill: skill_view to load it, then follow it "
            "INCLUDING " + ("Simulation Mode and " if mode == "sim" else "")
            + "the lean Decision Records (predict -> act -> reconcile) discipline.")
    mode_line = ("SIMULATION MODE IS ACTIVE (read $HERMES_SIM_SCENARIO); do NOT perform "
                 "real actions." if mode == "sim" else "This is a REAL run (Simulation Mode OFF).")
    parts = [head, mode_line, f"INTENT: {intent}."]
    if meanings:
        desc = "; ".join(f"{m.tag} = {meanings.get(m.tag, m.tag)}" for m in methods)
        parts.append(f"Methods, in preference order: {desc}.")
    parts.append(method_list_prompt(methods))
    if extra:
        parts.append(extra)
    parts.append(
        envelope.marker_map_block(plans_dir, slug, jsonl_clause=None)
        + " Write each record as ONE compact single-line JSON object on its own line, "
        "then a newline (valid JSONL — never pretty-print across lines, never "
        "concatenate two objects without a newline).")
    return "\n".join(parts)


def expected_terminal(methods: List[Method], default: str = "tombstone") -> str:
    """Lightweight oracle: 'success' if any success outcome exists (a reachable win),
    else 'exhaustion'. guard-halt is budget-driven and must be declared, not inferred."""
    if any(m.outcome == "success" for m in methods):
        return "success"
    if default == "progress":
        return "success"
    return "exhaustion"


def validate_expect(methods: List[Method], default: str, expect_terminal: str) -> None:
    """Consistency-check a declared expectation against the rules."""
    if expect_terminal == "guard_halt":
        return  # enforced by a budget in the prompt + an open frontier, not by rules
    inferred = expected_terminal(methods, default)
    if expect_terminal != inferred:
        raise ValueError(
            f"declared expect={expect_terminal!r} but the rules infer {inferred!r}; "
            "fix the rules or the expectation."
        )


if __name__ == "__main__":
    import json

    # backtrack-equivalent: two siblings fail, recover via cache -> verify success.
    bt = [
        Method("alfa", "tombstone", reason="primary network source down"),
        Method("bravo", "tombstone", reason="mirror network source down"),
        Method("charlie", "progress", opens=["delta"], reason="local cache hit"),
        Method("delta", "success", reason="verified valid JSON with key ok"),
    ]
    s = build_scenario("produce data with key ok (network preferred)", bt,
                       notes="backtrack: siblings fail, recover to cache->verify")
    validate(bt, "tombstone")
    validate_expect(bt, "tombstone", "success")
    assert expected_terminal(bt) == "success"
    assert s["rules"][0]["match"]["action_contains"] == "alfa"
    print("[OK] backtrack-equivalent builds; terminal=success")
    print(json.dumps(s, indent=2))
    print(method_list_prompt(bt))
    p = build_prompt("produce a data file with key ok", bt, "demo",
                     meanings={"alfa": "primary source", "bravo": "mirror",
                               "charlie": "cache", "delta": "verify"})
    assert "alfa" in p and "charlie" in p and "INTENT" in p and "journal.jsonl" in p
    print("[OK] build_prompt emits a runnable, tag-consistent prompt")

    # exhaustion-equivalent: nothing succeeds.
    ex = [Method("alfa", "tombstone", reason="sole source unreachable")]
    build_scenario("obtain data from the sole unreachable source", ex)
    validate_expect(ex, "tombstone", "exhaustion")
    assert expected_terminal(ex) == "exhaustion"
    print("[OK] exhaustion-equivalent builds; terminal=exhaustion")

    # overlap guard must trip.
    try:
        validate([Method("sign", "tombstone"), Method("countersign", "tombstone")], "tombstone")
        raise SystemExit("FAIL: overlap guard did not trip")
    except ValueError:
        print("[OK] overlap guard trips on sign/countersign")

    print("ALL BUILDER SELF-TESTS PASSED")
